BOT_NAME = 'Instasaver'
BOT_URL = 'https://t.me/saveinstapaper_bot'
DEVELOPER_NAME = 'DahaWong'
DEVELOPER_TELEGRAM_USERNAME = 'dahawong'
STUDIO_URL = 'https://dreamlong.design/'
REPOSITORY_URL = 'https://github.com/DahaWong/instasaver'